name: automerge

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'CI'
      
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
