# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CD

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set Up Mono
      run: sudo apt install gnupg ca-certificates ; 
       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF ;
       echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list ;
       sudo apt update ; sudo apt install mono-devel
    
    - name: Baixando Script Python
      run: | 
        curl https://raw.githubusercontent.com/MXClyde/MendixModelTools/master/Scripts/mxbuild.py -o mxbuild.py ;
        sed -i 's|{}/modeler|mono {}/modeler|g' mxbuild.py 

    - name: Gerando a Variaveis de ambiente
      run: echo "MXV="$(cat mx-version)  >> $GITHUB_ENV ; echo "MXNAME="$(cat mx-appname)  >> $GITHUB_ENV ; echo "MXR="$(cat mx-revision)  >> $GITHUB_ENV           

    - name: Criando as pasta necessárias para a geração do package
      run: mkdir exports ; mkdir mxLib ; mkdir builds 
       
    - name: Gerando Package .Mda
      run: python3 mxbuild.py -t "${{ secrets.TEAMSERVER }}" -u "${{ secrets.USER }}" -p "${{ secrets.PASS }}" -java $JAVA_HOME -r ${{ env.MXR }} -v ${{ env.MXV }} -d true -o project_${{ env.MXNAME }}_${{ env.MXV }}.mda
    
    - name: Verificando .Mda
      run: cd builds ; ls  
      

