# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Zipando o projeto para build
      - name: Zipando o projeto para build
        run: tar -zcf build.tar.gz .
        
      # Movendo o projeto zipado para a pasta build
      - name: Movendo o projeto zipado para a pasta build
        run: mkdir build ; mv build.tar.gz build ; cd build ; tar -zxf build.tar.gz . ; rm -f build.tar.gz
        
      # Clonando o projeto build-pack da Mendix para gera o Build
      - name: Movendo o projeto zipado para a pasta build
        run: cd .. ; git clone https://github.com/mendix/docker-mendix-buildpack.git
        
      # Configurando as pasta para geração do Build
      - name: Configurando as pasta para geração do Build
        run: mkdir deploy ; mv build docker-mendix-buildpack ; mv docker-mendix-buildpack deploy ; cd deploy ; cd docker-mendix-buildpack
  
      # Gerando a Variaveis de ambiente para o Build
      - name: Configurando as pasta para geração do Build
        run: |
          CF_BUILDPACK_VERSION=$(cat cf-buildpack.version) 
          ROOTFS_VERSION=$(cat rootfs.version)
          
      # Gerando o Build da Aplicação
      - name: Gerando o Build da Aplicação
        run: |
          docker build \
          --build-arg BUILD_PATH=build \
          --build-arg CF_BUILDPACK=$CF_BUILDPACK_VERSION \
          --build-arg ROOTFS_IMAGE=$ROOTFS_VERSION \
          -t mendix/mendix-buildpack-ci .
          
                # Gerando o Build da Aplicação
      - name: Gerando o Build da Aplicação
        run: |
          ID_DOCKER=$(docker run -it \
          -e ADMIN_PASSWORD=Password1! \
          -e DATABASE_ENDPOINT=jdbc:hsqldb:file:~/data/database/mendix \
          -e MXRUNTIME_DatabaseType=HSQLDB \
          -e MXRUNTIME_DatabaseJdbcUrl=jdbc:hsqldb:file:~/data/database/mendix \
          mendix/mendix-buildpack-ci)
      
      # ID do Container
      - name: ID do Container
        run: echo $ID_DOCKER
